# Generated by Django 3.0.8 on 2022-09-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
