# Generated by Django 3.0.8 on 2022-09-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_app', '0002_auto_20220902_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
