# Generated by Django 3.0.8 on 2022-09-09 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader_app', '0003_auto_20220905_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
